# Generated by Django 5.1.3 on 2024-11-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergy',
            table='allergy',
        ),
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
        migrations.AlterModelTable(
            name='food',
            table='food',
        ),
        migrations.AlterModelTable(
            name='foodallergy',
            table='food_allergy',
        ),
        migrations.AlterModelTable(
            name='foodtype',
            table='foodtype',
        ),
    ]
