# Generated by Django 5.1.3 on 2024-11-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_recommendation', '0002_alter_allergy_table_alter_city_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table='food_type',
        ),
    ]
